//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_spaceship : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 leftstick
        {
            get
            {
                return SteamVR_Actions.spaceship_leftstick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 rightstick
        {
            get
            {
                return SteamVR_Actions.spaceship_rightstick;
            }
        }
        
        public virtual SteamVR_Action_Boolean fire
        {
            get
            {
                return SteamVR_Actions.spaceship_fire;
            }
        }
    }
}
